###CREATE USER
POST http://localhost:4000/api/auth
content-type: application/json

{
    "user": {
        "username": "ratz",
        "email": "test@test.com",
        "password": "12345"
 }
}

###LOGIN USER

POST http://localhost:4000/api/auth/login
content-type: application/json

{
    "user": {
        "email": "test@test.com",
        "password": "12345"
 }
}

